-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("dms run")
	hl.exec_cmd("wl-paste -p --watch wl-copy -cp") -- Hack for disabling middle click paste
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		kb_layout = "cz,us",
		numlock_by_default = true,
		follow_mouse = 1,
		kb_options = "caps:swapescape,grp:win_space_toggle,compose:rctrl",
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		mouse_move_enables_dpms = true,
		enable_swallow = true,
		background_color = "000000",
		middle_click_paste = false,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "easeOutQuint", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "easeOutQuint", style = "popin 80%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "easeOutQuint" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "easeOutQuint" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "easeOutQuint" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 2, bezier = "easeOutQuint" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "easeOutQuint", style = "slide" })

hl.window_rule({ match = { title = "file_progress" }, float = true })
hl.window_rule({ match = { title = "confirm" }, float = true })
hl.window_rule({ match = { title = "dialog" }, float = true })
hl.window_rule({ match = { title = "download" }, float = true })
hl.window_rule({ match = { title = "notification" }, float = true })
hl.window_rule({ match = { title = "error" }, float = true })
hl.window_rule({ match = { title = "splash" }, float = true })
hl.window_rule({ match = { title = "confirmreset" }, float = true })
hl.window_rule({ match = { title = "Open File" }, float = true })
hl.window_rule({ match = { title = "branchdialog" }, float = true })
hl.window_rule({ match = { title = "Lxappearance" }, float = true })
hl.window_rule({ match = { title = "viewnior" }, float = true })
hl.window_rule({ match = { title = "feh" }, float = true })
hl.window_rule({ match = { title = "pavucontrol-qt" }, float = true })
hl.window_rule({ match = { title = "pavucontrol" }, float = true })
hl.window_rule({ match = { title = "file-roller" }, float = true })
hl.window_rule({ match = { title = "^(Media viewer)$" }, float = true })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { title = "Rofi" }, float = true, no_anim = true })
hl.window_rule({ match = { title = "wlogout" }, float = true, fullscreen = true })
hl.window_rule({ match = { title = "^(Alacritty)$" }, fullscreen = true })
hl.window_rule({
	match = { title = "^(Volume Control)$" },
	float = true,
	size = { 800, 600 },
	move = { "75", "44%" },
})
hl.window_rule({ match = { title = "mpv" }, idle_inhibit = "focus" })
hl.window_rule({ match = { title = "firefox" }, idle_inhibit = "fullscreen" })
hl.window_rule({
	name = "xwayland-video-bridge-fixes",
	match = { class = "xwaylandvideobridge" },
	no_initial_focus = true,
	no_focus = true,
	no_anim = true,
	no_blur = true,
	max_size = { 1, 1 },
	opacity = 0.0,
})
hl.window_rule({
	name = "ueberzugpp-image-preview",
	match = { class = "^(ueberzug.*)$" },
	float = true,
	no_anim = true,
	no_shadow = true,
	no_focus = true,
	rounding = 0,
})

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

require("./custom/*")
