-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

require("globals")

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("dms run")
	hl.exec_cmd("wl-paste -p --watch wl-copy -cp") -- Hack for disabling middle click paste
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		kb_layout = "cz,us",
		numlock_by_default = true,
		follow_mouse = 1,
		kb_options = "caps:swapescape,grp:win_space_toggle,compose:rctrl",
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		mouse_move_enables_dpms = true,
		enable_swallow = true,
		background_color = "000000",
		middle_click_paste = false,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

require("./custom/*")
