-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-8", mode = "1920x1080@60.000", position = "1920x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-9", mode = "1920x1080@60.000", position = "3840x0", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", mode = "1920x1200@60.003", position = "0x455", scale = 1, vrr = 0 })
